version: '3'

services:

  mongodb:
    container_name: wanderlust-db
    image: monkeydmagnas007/wanderlust-db:beta-version 
    restart: always
    ports:
      - 27017:27017
    networks:
      - wanderlust
    command: ["/bin/bash", "-c", "mongod --bind_ip_all & sleep 5 && mongoimport --db wanderlust --collection posts --file /sample_posts.json --jsonArray"]

  backend:
    image: monkeydmagnas007/wanderlust-backend:beta-version
    depends_on:
      - mongodb
    container_name: backend
    restart: always
    environment: 
     - PORT=5000
     - MONGODB_URI=mongodb://mongodb:27017/wanderlust
     - CORS_ORIGIN=http://20.119.78.4:5173
     - FRONTEND_URL=http://20.119.78.4:5173
    ports:
      - 5000:5000
    networks:
      - wanderlust

  frontend:
    container_name: frontend
    image: monkeydmagnas007/wanderlust-front:beta-version
    environment:
      - VITE_API_PATH=http://20.119.78.4:5000
    ports:
      - 5173:5173
    networks:
      - wanderlust

networks:
  wanderlust:
    name: "wanderlust"
    driver: bridge