name: Wanderlust CICD

on:
  push:
    branches:
      - staging

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/
          push: true
          tags: monkeydmagnas007/wanderlust-git:frontend
          
  Backend-Build:
      runs-on: ubuntu-latest
      needs: frontend-build
      steps:
        
      - name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      -  name: Build and push
         uses: docker/build-push-action@v6
         with:
            context: ./backend/
            push: true
            tags: monkeydmagnas007/wanderlust-git:backend

  File-Transfer-dockercompose:
    name: Copy Docker Compose file to Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.yaml"
          target: /home/ubuntu/
  
  File-transfer-bash-script:  
    name: Copy Docker Compose file to Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "docker.sh"
          target: /home/ubuntu/

  Deploy:
  - name: multiple command
    uses: appleboy/ssh-action@v1
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.SSH_KEY }}
      port: ${{ secrets.PORT }}
      script: |
        whoami
        ls -al